[tools]
luau-lsp = "johnnymorganz/luau-lsp@1.60.0"
lune = "horsenuggets/lune@0.10.4-horse.6.0"
rojo = "rojo-rbx/rojo@7.6.0"
stylua = "johnnymorganz/stylua@2.3.1"
wally = "horsenuggets/wally@0.3.2-horse.4.1"
